In [1]:
import numpy as np
from sqlalchemy import engine

In [2]:
import pandas as pd
df = pd.read_csv("nyc_311_requests.csv")
print(f"Total rows: {df.shape[0]}")
df.head()

C:\Users\RONO\AppData\Local\Temp\ipykernel_19012\805106684.py:2: DtypeWarning: Columns (0: taxi_company_borough) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("nyc_311_requests.csv")

Total rows: 500000

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,descriptor_2,location_type,incident_zip,...,location,bridge_highway_name,bridge_highway_direction,road_ramp,bridge_highway_segment,landmark,taxi_pick_up_location,facility_type,taxi_company_borough,vehicle_type
0,40287734,2020-09-25T15:43:34.000,2020-09-25T15:43:34.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Gate,Park,10451.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,40935119,2020-09-25T15:51:00.000,2020-09-25T15:51:00.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Other,Park,10465.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,40962915,2020-09-25T15:51:54.000,2020-09-25T15:51:54.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Gate,Park,10473.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,41499422,2020-09-24T13:24:00.000,2020-09-24T13:24:00.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Sign,Park,10461.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,41680133,2020-09-25T16:00:27.000,2020-09-25T16:00:27.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Playground Equipment,Park,10468.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Data preprocessing

In [3]:
# 

df = df[[
    'unique_key',
    'created_date',
    'closed_date',
    'agency',
    'agency_name',
    'complaint_type',
    'descriptor',
    'location_type',
    'incident_zip',
    'city',
    'borough',
    'status',
    'resolution_description',
    'latitude',
    'longitude',
    'resolution_action_updated_date'
]]

In [4]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,city,borough,status,resolution_description,latitude,longitude,resolution_action_updated_date
0,40287734,2020-09-25T15:43:34.000,2020-09-25T15:43:34.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10451.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-25T15:43:30.000
1,40935119,2020-09-25T15:51:00.000,2020-09-25T15:51:00.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10465.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-25T15:50:58.000
2,40962915,2020-09-25T15:51:54.000,2020-09-25T15:51:54.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10473.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2021-01-04T15:42:12.000
3,41499422,2020-09-24T13:24:00.000,2020-09-24T13:24:00.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10461.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-24T13:23:57.000
4,41680133,2020-09-25T16:00:27.000,2020-09-25T16:00:27.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10468.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-25T16:00:24.000

In [5]:
df.isnull().sum()

unique_key                             0
created_date                           0
closed_date                         4905
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          7065
location_type                     135329
incident_zip                       14817
city                               32258
borough                             3308
status                                 0
resolution_description             50183
latitude                           17347
longitude                          17347
resolution_action_updated_date      3056
dtype: int64

In [6]:
df['city'] = df['city'].str.upper().str.strip()

In [7]:
df['city'].unique()

<StringArray>
[              'BRONX',            'NEW YORK',            'BROOKLYN',
    'LONG ISLAND CITY',             'ASTORIA',        'FOREST HILLS',
            'FLUSHING',           'REGO PARK',       'COLLEGE POINT',
             'JAMAICA',       'EAST ELMHURST',            'WOODSIDE',
     'JACKSON HEIGHTS',           'SUNNYSIDE',             'BAYSIDE',
            'ELMHURST',       'STATEN ISLAND',             'MASPETH',
              'CORONA',          'OZONE PARK',       'RICHMOND HILL',
        'FAR ROCKAWAY', 'SOUTH RICHMOND HILL',         'LITTLE NECK',
           'RIDGEWOOD',      'QUEENS VILLAGE',         'KEW GARDENS',
    'SOUTH OZONE PARK',        'HOWARD BEACH',            'ROSEDALE',
             'ARVERNE',     'CAMBRIA HEIGHTS',      'MIDDLE VILLAGE',
     'OAKLAND GARDENS',              'HOLLIS', 'SPRINGFIELD GARDENS',
           'GLEN OAKS',         'FLORAL PARK',        'BREEZY POINT',
       'FRESH MEADOWS',           'BELLEROSE',                   nan,
           'MANHATTAN',              'QUEENS',           'WOODHAVEN',
        'SAINT ALBANS',          'WHITESTONE',       'ROCKAWAY PARK',
       'NEW HYDE PARK',   'LAGUARDIA AIRPORT']
Length: 50, dtype: str

In [8]:
df['incident_zip'].unique()

array([10451., 10465., 10473., 10461., 10468., 10462., 10014., 11238.,
       11101., 11211., 11208., 11105., 10027., 11232., 11237., 10013.,
       11375., 11218., 11206., 11355., 10065., 11103., 10002., 11214.,
       10459., 10021., 10029., 10035., 11374., 10474., 10001., 11220.,
       10456., 10038., 10075., 11356., 10012., 11221., 11106., 11216.,
       11223., 10128., 10010., 11102., 11435., 11229., 11249., 10022.,
       10454., 11205., 11207., 11235., 10460., 11219., 11228., 11369.,
       11377., 10028., 11372., 11104., 11236., 11201., 11212., 11222.,
       11215., 11361., 11373., 10302., 10305., 10011., 11226., 11233.,
       10030., 10452., 10007., 10025., 10018., 11204., 10306., 11230.,
       11378., 11354., 10032., 10301., 11368., 11417., 10026., 10455.,
       11432., 10463., 10019., 10458., 10017., 11418., 11217., 11225.,
       10466., 10016., 10453., 11231., 11209., 11693., 10310., 10033.,
       10303., 10314., 11210., 11691., 10457., 10475., 10036., 11224.,
       11434., 11419., 10003., 11234., 11362., 11385., 10309., 10467.,
       10472., 10024., 10304., 10006., 11203., 11428., 11213., 11416.,
       10037., 11694., 11415., 10470., 10312., 11420., 11429., 10005.,
       10044., 11367., 11109., 11414., 10023., 10105., 11422., 11692.,
       10308., 11411., 10004., 11379., 10469., 10034., 11364., 11423.,
       11413., 11239., 10009., 11433., 11358., 10031., 11436., 11427.,
       11004., 11001., 10282., 11370., 11697., 10471., 11366., 10307.,
       10039., 10280., 10168., 10172., 10169., 10020., 10151., 11360.,
       11426.,    nan, 11365., 11421., 11412., 10464., 10040., 11357.,
       11430., 10121., 10279., 11371., 10119., 11363., 10173., 11359.,
       10177., 10000., 10174., 11040., 10178., 10069., 11005., 12345.,
       10171., 10120., 10112., 10278., 10281., 10041., 10165., 11695.,
       10162., 10103., 10118., 11242., 10154., 10152., 10271., 10110.,
       10155., 10045., 10123., 11251., 10170., 10166., 10122., 10158.,
       10179., 10111., 10106., 10055., 10176., 11241., 10107., 10115.])

In [9]:
print((df['incident_zip'] == 'N/A').sum())

0

In [10]:
print(df['borough'].value_counts(dropna=False))

borough
BROOKLYN         153460
QUEENS           126104
MANHATTAN         98943
BRONX             88211
STATEN ISLAND     27345
NaN                3308
Unspecified        2629
Name: count, dtype: int64

In [11]:
# Replace 'Unspecified' and empty strings with None
df['borough'] = df['borough'].replace({"Unspecified":np.nan})
df['borough'] = df['borough'].str.upper().str.strip()

In [12]:
df['borough'].value_counts(dropna=False)

borough
BROOKLYN         153460
QUEENS           126104
MANHATTAN         98943
BRONX             88211
STATEN ISLAND     27345
NaN                5937
Name: count, dtype: int64

In [13]:
df.columns

Index(['unique_key', 'created_date', 'closed_date', 'agency', 'agency_name',
       'complaint_type', 'descriptor', 'location_type', 'incident_zip', 'city',
       'borough', 'status', 'resolution_description', 'latitude', 'longitude',
       'resolution_action_updated_date'],
      dtype='str')

In [14]:
df.isna().sum()

unique_key                             0
created_date                           0
closed_date                         4905
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          7065
location_type                     135329
incident_zip                       14817
city                               32258
borough                             5937
status                                 0
resolution_description             50183
latitude                           17347
longitude                          17347
resolution_action_updated_date      3056
dtype: int64

In [15]:
# A complaint with no borough is essentially an incomplete record

df = df.dropna(subset=['borough'])

In [16]:
non_nullable_columns = [
    'unique_key',
    'created_date',
    'agency',
    'agency_name',
    'complaint_type',
    'borough',
    'status'
]

print(df[non_nullable_columns].isnull().sum())

unique_key        0
created_date      0
agency            0
agency_name       0
complaint_type    0
borough           0
status            0
dtype: int64

In [17]:
df.isna().sum()

unique_key                             0
created_date                           0
closed_date                         4872
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          7009
location_type                     132541
incident_zip                        8924
city                               26356
borough                                0
status                                 0
resolution_description             50161
latitude                           11442
longitude                          11442
resolution_action_updated_date      3047
dtype: int64

In [18]:
df.shape

(494063, 16)

In [19]:
df.dtypes

unique_key                          int64
created_date                          str
closed_date                           str
agency                                str
agency_name                           str
complaint_type                        str
descriptor                            str
location_type                         str
incident_zip                      float64
city                                  str
borough                               str
status                                str
resolution_description                str
latitude                          float64
longitude                         float64
resolution_action_updated_date        str
dtype: object

In [20]:
df.head()

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,city,borough,status,resolution_description,latitude,longitude,resolution_action_updated_date
0,40287734,2020-09-25T15:43:34.000,2020-09-25T15:43:34.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10451.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-25T15:43:30.000
1,40935119,2020-09-25T15:51:00.000,2020-09-25T15:51:00.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10465.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-25T15:50:58.000
2,40962915,2020-09-25T15:51:54.000,2020-09-25T15:51:54.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10473.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2021-01-04T15:42:12.000
3,41499422,2020-09-24T13:24:00.000,2020-09-24T13:24:00.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10461.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-24T13:23:57.000
4,41680133,2020-09-25T16:00:27.000,2020-09-25T16:00:27.000,DPR,Department of Parks and Recreation,Maintenance or Facility,Structure - Outdoors,Park,10468.0,BRONX,BRONX,Closed,The Department of Parks and Recreation has com...,NaN,NaN,2020-09-25T16:00:24.000

In [21]:
# Fix dates 
df['created_date'] = pd.to_datetime(df['created_date'], errors='coerce')
df['closed_date'] = pd.to_datetime(df['closed_date'], errors='coerce')
df['resolution_action_updated_date'] = pd.to_datetime(df['resolution_action_updated_date'], errors='coerce')

# Fix ZIP (convert float back to clean string) 
df['incident_zip'] = df['incident_zip'].apply(
    lambda x: str(int(x)).zfill(5) if pd.notnull(x) else None
)

# Verify 
print(df.dtypes)

unique_key                                 int64
created_date                      datetime64[us]
closed_date                       datetime64[us]
agency                                       str
agency_name                                  str
complaint_type                               str
descriptor                                   str
location_type                                str
incident_zip                                 str
city                                         str
borough                                      str
status                                       str
resolution_description                       str
latitude                                 float64
longitude                                float64
resolution_action_updated_date    datetime64[us]
dtype: object

In [22]:
invalid_zips = ['00000', 'N/A', '', ' ']
for val in invalid_zips:
    count = (df['incident_zip'] == val).sum()
    print(f"'{val}': {count} rows")

'00000': 0 rows
'N/A': 0 rows
'': 0 rows
' ': 0 rows

In [23]:
df.isna().sum()

unique_key                             0
created_date                           0
closed_date                         4872
agency                                 0
agency_name                            0
complaint_type                         0
descriptor                          7009
location_type                     132541
incident_zip                        8924
city                               26356
borough                                0
status                                 0
resolution_description             50161
latitude                           11442
longitude                          11442
resolution_action_updated_date      3047
dtype: int64

### Top complaints

In [25]:
# top 10 complaint types
print(df['complaint_type'].value_counts().head(20))

complaint_type
HEAT/HOT WATER                         56974
Noise - Residential                    50336
Request Large Bulky Item Collection    45808
Illegal Parking                        42504
Blocked Driveway                       27824
Street Condition                       18113
Street Light Condition                 13562
Electronics Waste Appointment          10927
Noise                                  10286
Missed Collection (All Materials)       9495
Water System                            9428
Abandoned Vehicle                       9171
Noise - Street/Sidewalk                 9074
General Construction/Plumbing           9030
UNSANITARY CONDITION                    8267
Consumer Complaint                      7869
Noise - Commercial                      7693
Traffic Signal Condition                7069
Noise - Vehicle                         7027
Derelict Vehicles                       6877
Name: count, dtype: int64